version: 2

sources:
  - name: raw
    database: USER_DB_COYOTE
    schema: raw
    description: "Schema which stores raw tables from ETL"
    tables:
      - name: user_session_channel
        identifier: user_session_channel
      - name: session_timestamp
        identifier: session_timestamp
  - name: analytics
    database: USER_DB_COYOTE
    schema: analytics
    description: "Schema with stores analytics tables (ELT)"
    tables:
    - name: session_summary
      identifier: session_summary
      description: "Complete session info"